[build]
command = "npm run build-all"
publish = "client"


[dev]
port = 8888
command = "npm run start-all"
targetPort = 3000


[functions]
directory = "server/server/functions"
node_bundler = "nft"
included_files = ["server/**/*", "client/**/*.html"]


[[redirects]]
from = "/"
to = "/.netlify/functions/render_pages"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/functions/render_pages"
status = 200


[context.dev.environment]
CLIENT_DEV_ORIGIN = "http://127.0.0.1:3000"
